# Generated by Django 2.2.1 on 2019-08-15 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(default='Одежда', max_length=120, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='work_time',
            field=models.CharField(default='Мебель', max_length=120, verbose_name='Рабочее время'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
    ]
